<?php

return [
    'app_username' => 'importuser',
    'app_password_hash' => '$2y$10$exampleHashOnlyReplaceInLocalConfig',
    // Jedina ciljna domena aplikacije. Docker override: UPP_TARGET_DOMAIN=https://dinamic.loc
    'target_domain' => 'https://dinamic.hr',
    'woocommerce_consumer_key' => 'ck_xxx',
    'woocommerce_consumer_secret' => 'cs_xxx',
    'woocommerce_verify_ssl' => true,
    // Skladišta koja ulaze u WooCommerce ukupnu web-zalihu i prikaz na artiklu.
    'warehouse_map' => [
        '202' => ['name' => 'Čakovec', 'address' => 'Bana Jelačića 4'],
        '204' => ['name' => 'Virovitica', 'address' => 'S. Radića 77'],
        '205' => ['name' => 'Čakovec', 'address' => 'Svetojelenska 15'],
        '208' => ['name' => 'Koprivnica', 'address' => 'B. Radića 23'],
        '209' => ['name' => 'Varaždin', 'address' => 'Optujska 50'],
        '701' => ['name' => 'Skladište', 'address' => ''],
    ],
    'stock_included_warehouses' => ['202', '204', '205', '208', '209', '701'],
    'new_product_status' => 'draft',
    'unknown_category_behavior' => 'skip_category',
    'unknown_brand_behavior' => 'continue',
    'upload_max_bytes' => 52428800,
    'category_map' => [
        '102' => 'lezajevi-pogona-bb-osovine',
        '0801' => 'lezajevi-pogona-bb-osovine',
        '0802' => 'lezajevi-volana-vilica',
        '0804' => 'glave-i-dijelovi-glava',
        '0806' => 'kocnice',
        '0807' => 'kormila-lule-volana-vilice-i-nastavci-v',
        '0808' => 'lule-sjedala-selne-sjedala-vijci',
        '0810' => 'kotaci',
        '0812' => 'lanci-spojnice',
        '0813' => 'lancanici-prednji-kurble',
        '0814' => 'lancanici-zadnji',
        '0815' => 'mjenjaci',
        '0816' => 'rucice-mjenjaca',
        '0818' => 'obruci-zbice-niple-trake',
        '0820' => 'ostali-dijelovi',
        '0822' => 'pedale-blokeji',
        '0824' => 'rucice-gripovi-trake-volana',
        '0826' => 'sajle-buziri',
        '0830' => 'sjedala-i-navlake-sjedala',
        '0902' => 'alati',
        '0904' => 'bidoni-i-nosaci-bidona',
        '0905' => 'prtljaznici',
        '0906' => 'blatobrani-lancobrani',
        '0907' => 'rukavice',
        '0908' => 'kacige',
        '0909' => 'naocale',
        '0910' => 'odjeca-obuca-marame',
        '0911' => 'kosarice-i-dijelovi-kosarica',
        '0912' => 'ciklokompjutori-satovi',
        '0914' => 'lokoti',
        '0916' => 'ostala-oprema',
        '0920' => 'podupiraci-pomocni-kotaci-nosaci-bicikla',
        '0922' => 'pumpe-pribori-za-krpanje-co2-tubeless',
        '0924' => 'djecje-sjedalice',
        '0926' => 'svijetla-katadiopteri',
        '0928' => 'torbice-i-bisage',
        '0930' => 'zvona-trube-retrovizori',
        '1082' => 'spring',
        '1083' => 'scott',
        '1085' => 'rock-machine',
        '1086' => 'wob',
        '1088' => 'djecji',
        '108T' => 'testni',
    ],
    'brand_map' => [
        'DI' => 'Dinamic', 'FA' => 'Falcon', 'JY' => 'Joytech', 'KM' => 'KMC',
        'MA' => 'Marcon', 'ME' => 'Messingschlager', 'MG' => 'Monte Grappa',
        'MT' => 'Mitas', 'MI' => 'Mighty', 'HT' => 'HTP', 'PT' => 'Park Tool',
        'RM' => 'Rock Machine', 'RX' => 'Remerx', 'RS' => 'RMS', 'SA' => 'Saccon',
        'SC' => 'Scott', 'SH' => 'Shimano', 'SI' => 'Sigma', 'SP' => 'Spring',
        'SW' => 'Schwalbe', 'SY' => 'Syncros', 'TH' => 'Thun', 'TL' => 'Trelock',
        'UN' => 'Unior', 'VA' => 'VAR', 'VE' => 'Velosteel', 'VL' => 'Velo',
        'WB' => 'WOB', 'ZO' => 'Zoom',
    ],
    'enable_test_scripts' => false,
];
